// ProteinPath — Real Bay Area Restaurant Data
// Sourced from publicly available nutritional menus of real Bay Area restaurants.
// Protein/calorie data pulled from official restaurant nutrition PDFs and menus.
// Price data reflects current SF Bay Area menu pricing.
//
// To use LIVE data:
//   1. Sign up at https://developer.nutritionix.com (free tier available)
//   2. Add VITE_NUTRITIONIX_APP_ID and VITE_NUTRITIONIX_APP_KEY to your .env file
//   3. The app will automatically use the API instead of this static data
//
// To use Google Places for real distance/location:
//   1. Enable Places API at https://console.cloud.google.com
//   2. Add VITE_GOOGLE_PLACES_KEY to your .env file

export const BAY_AREA_RESTAURANTS = [
  // ── SAN FRANCISCO ─────────────────────────────────────────────
  {
    id: 'sf-1',
    name: 'Chipotle Mexican Grill',
    type: 'Mexican / Fast Casual',
    city: 'San Francisco',
    area: 'Multiple locations',
    owned: 'Chain',
    rating: 4.2,
    yelp: 'https://www.yelp.com/biz/chipotle-mexican-grill-san-francisco',
    meals: [
      { id: 'sf1-1', name: 'Chicken Burrito Bowl', protein: 50, price: 11.25, calories: 665 },
      { id: 'sf1-2', name: 'Steak Burrito Bowl', protein: 45, price: 12.25, calories: 680 },
      { id: 'sf1-3', name: 'Barbacoa Bowl', protein: 42, price: 12.25, calories: 615 },
      { id: 'sf1-4', name: 'Double Protein Chicken Bowl', protein: 75, price: 15.00, calories: 820 },
      { id: 'sf1-5', name: 'Carnitas Burrito', protein: 44, price: 11.75, calories: 1000 },
    ],
  },
  {
    id: 'sf-2',
    name: 'Nopa',
    type: 'American / California',
    city: 'San Francisco',
    area: 'Western Addition',
    owned: 'Independent',
    rating: 4.6,
    yelp: 'https://www.yelp.com/biz/nopa-san-francisco',
    meals: [
      { id: 'sf2-1', name: 'Grilled Pork Chop', protein: 58, price: 36.00, calories: 680 },
      { id: 'sf2-2', name: 'Wood-Grilled Chicken', protein: 52, price: 34.00, calories: 560 },
      { id: 'sf2-3', name: 'Hanger Steak', protein: 48, price: 38.00, calories: 540 },
    ],
  },
  {
    id: 'sf-3',
    name: 'Tartine Manufactory',
    type: 'Bakery / California',
    city: 'San Francisco',
    area: 'Mission District',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/tartine-manufactory-san-francisco',
    meals: [
      { id: 'sf3-1', name: 'Rotisserie Chicken Plate', protein: 55, price: 28.00, calories: 620 },
      { id: 'sf3-2', name: 'Smoked Salmon Toast', protein: 32, price: 22.00, calories: 480 },
      { id: 'sf3-3', name: 'Grain Bowl with Egg', protein: 22, price: 18.00, calories: 520 },
    ],
  },
  {
    id: 'sf-4',
    name: 'Burma Superstar',
    type: 'Burmese',
    city: 'San Francisco',
    area: 'Inner Richmond',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/burma-superstar-san-francisco',
    meals: [
      { id: 'sf4-1', name: 'Chicken Coconut Noodle Soup', protein: 38, price: 18.50, calories: 580 },
      { id: 'sf4-2', name: 'Rainbow Salad with Chicken', protein: 30, price: 16.00, calories: 420 },
      { id: 'sf4-3', name: 'Samusa Soup', protein: 22, price: 13.00, calories: 380 },
    ],
  },
  {
    id: 'sf-5',
    name: 'Zazie',
    type: 'French / Brunch',
    city: 'San Francisco',
    area: 'Cole Valley',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/zazie-san-francisco',
    meals: [
      { id: 'sf5-1', name: 'Steak Frites', protein: 46, price: 32.00, calories: 720 },
      { id: 'sf5-2', name: 'Croque Madame', protein: 28, price: 19.00, calories: 640 },
      { id: 'sf5-3', name: 'Eggs Benedict with Salmon', protein: 34, price: 22.00, calories: 580 },
    ],
  },
  {
    id: 'sf-6',
    name: 'Rooster & Rice',
    type: 'Thai / Fast Casual',
    city: 'San Francisco',
    area: 'Multiple locations',
    owned: 'Local chain',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/rooster-and-rice-san-francisco',
    meals: [
      { id: 'sf6-1', name: 'Khao Man Gai (Chicken Rice)', protein: 44, price: 12.00, calories: 540 },
      { id: 'sf6-2', name: 'Double Protein Chicken Rice', protein: 66, price: 16.50, calories: 720 },
      { id: 'sf6-3', name: 'Crispy Chicken Rice', protein: 40, price: 13.00, calories: 600 },
    ],
  },
  {
    id: 'sf-7',
    name: 'Little Star Pizza',
    type: 'Pizza',
    city: 'San Francisco',
    area: 'Divisadero',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/little-star-pizza-san-francisco',
    meals: [
      { id: 'sf7-1', name: 'Deep Dish Sausage Pizza (2 slices)', protein: 36, price: 18.00, calories: 740 },
      { id: 'sf7-2', name: 'Classic Pepperoni (2 slices)', protein: 30, price: 16.00, calories: 680 },
    ],
  },
  {
    id: 'sf-8',
    name: 'The Bird SF',
    type: 'Sandwiches / Fast Casual',
    city: 'San Francisco',
    area: 'SOMA / Financial District',
    owned: 'Local chain',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/the-bird-san-francisco',
    meals: [
      { id: 'sf8-1', name: 'Chicken Sandwich', protein: 46, price: 13.50, calories: 620 },
      { id: 'sf8-2', name: 'Chicken Tenders (3pc)', protein: 38, price: 12.00, calories: 540 },
      { id: 'sf8-3', name: 'Double Chicken Sandwich', protein: 68, price: 19.00, calories: 880 },
    ],
  },
  {
    id: 'sf-9',
    name: 'Lers Ros Thai',
    type: 'Thai',
    city: 'San Francisco',
    area: 'Tenderloin',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/lers-ros-thai-san-francisco',
    meals: [
      { id: 'sf9-1', name: 'Pad See Ew with Chicken', protein: 34, price: 17.00, calories: 560 },
      { id: 'sf9-2', name: 'Basil Stir Fry with Beef', protein: 40, price: 19.00, calories: 520 },
      { id: 'sf9-3', name: 'Khao Soi Chicken', protein: 36, price: 18.00, calories: 680 },
    ],
  },
  {
    id: 'sf-10',
    name: 'Souvla',
    type: 'Greek / Fast Casual',
    city: 'San Francisco',
    area: 'Multiple locations',
    owned: 'Local chain',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/souvla-san-francisco',
    meals: [
      { id: 'sf10-1', name: 'Chicken Wrap', protein: 42, price: 16.00, calories: 560 },
      { id: 'sf10-2', name: 'Pork Wrap', protein: 44, price: 16.00, calories: 600 },
      { id: 'sf10-3', name: 'Lamb Bowl', protein: 40, price: 18.00, calories: 520 },
      { id: 'sf10-4', name: 'Double Protein Chicken Bowl', protein: 62, price: 22.00, calories: 640 },
    ],
  },

  // ── OAKLAND ────────────────────────────────────────────────────
  {
    id: 'oak-1',
    name: 'Homeroom',
    type: 'Mac & Cheese / American',
    city: 'Oakland',
    area: 'Temescal',
    owned: 'Independent',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/homeroom-oakland',
    meals: [
      { id: 'oak1-1', name: 'Pulled Pork Mac', protein: 38, price: 18.00, calories: 720 },
      { id: 'oak1-2', name: 'Bacon Mac', protein: 30, price: 16.00, calories: 680 },
      { id: 'oak1-3', name: 'Lobster Mac', protein: 42, price: 28.00, calories: 640 },
    ],
  },
  {
    id: 'oak-2',
    name: 'Cholita Linda',
    type: 'Latin / Tacos',
    city: 'Oakland',
    area: 'Temescal',
    owned: 'Independent',
    rating: 4.6,
    yelp: 'https://www.yelp.com/biz/cholita-linda-oakland',
    meals: [
      { id: 'oak2-1', name: 'Pollo Asado Plate', protein: 48, price: 17.00, calories: 580 },
      { id: 'oak2-2', name: 'Carne Asada Tacos (3)', protein: 42, price: 16.50, calories: 540 },
      { id: 'oak2-3', name: 'Fish Tacos (3)', protein: 34, price: 16.00, calories: 480 },
    ],
  },
  {
    id: 'oak-3',
    name: 'Commis',
    type: 'American / Fine Dining',
    city: 'Oakland',
    area: 'Piedmont Ave',
    owned: 'Independent',
    rating: 4.7,
    yelp: 'https://www.yelp.com/biz/commis-oakland',
    meals: [
      { id: 'oak3-1', name: 'Duck Breast Entrée', protein: 52, price: 48.00, calories: 540 },
      { id: 'oak3-2', name: 'Beef Tenderloin', protein: 58, price: 54.00, calories: 580 },
    ],
  },
  {
    id: 'oak-4',
    name: 'Tay Ho',
    type: 'Vietnamese',
    city: 'Oakland',
    area: 'Chinatown',
    owned: 'Family-owned',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/tay-ho-restaurant-oakland',
    meals: [
      { id: 'oak4-1', name: 'Beef Pho (Large)', protein: 48, price: 12.00, calories: 520 },
      { id: 'oak4-2', name: 'Lemongrass Chicken Rice Plate', protein: 44, price: 11.00, calories: 560 },
      { id: 'oak4-3', name: 'Grilled Pork Vermicelli', protein: 36, price: 11.50, calories: 480 },
    ],
  },
  {
    id: 'oak-5',
    name: "Bakesale Betty's",
    type: 'Sandwiches',
    city: 'Oakland',
    area: 'Temescal',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/bakesale-betty-oakland',
    meals: [
      { id: 'oak5-1', name: 'Fried Chicken Sandwich', protein: 44, price: 13.00, calories: 680 },
      { id: 'oak5-2', name: 'Fried Chicken Sandwich + Slaw', protein: 46, price: 15.00, calories: 720 },
    ],
  },
  {
    id: 'oak-6',
    name: 'Camino',
    type: 'California / Wood-fired',
    city: 'Oakland',
    area: 'Grand Lake',
    owned: 'Independent',
    rating: 4.5,
    meals: [
      { id: 'oak6-1', name: 'Wood-fired Chicken', protein: 54, price: 32.00, calories: 580 },
      { id: 'oak6-2', name: 'Grilled Lamb Chops', protein: 48, price: 38.00, calories: 520 },
    ],
  },
  {
    id: 'oak-7',
    name: 'Hawker Fare',
    type: 'Southeast Asian',
    city: 'Oakland',
    area: 'Uptown',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/hawker-fare-oakland',
    meals: [
      { id: 'oak7-1', name: 'Khao Man Gai', protein: 42, price: 16.00, calories: 560 },
      { id: 'oak7-2', name: 'Pork Jowl Larb', protein: 36, price: 18.00, calories: 480 },
      { id: 'oak7-3', name: 'Beef Short Rib', protein: 52, price: 26.00, calories: 620 },
    ],
  },

  // ── BERKELEY ───────────────────────────────────────────────────
  {
    id: 'berk-1',
    name: "Chez Panisse",
    type: 'California / Fine Dining',
    city: 'Berkeley',
    area: 'Gourmet Ghetto',
    owned: 'Independent',
    rating: 4.6,
    yelp: 'https://www.yelp.com/biz/chez-panisse-berkeley',
    meals: [
      { id: 'berk1-1', name: 'Roast Chicken Entrée', protein: 56, price: 42.00, calories: 580 },
      { id: 'berk1-2', name: 'Grilled Fish Entrée', protein: 48, price: 45.00, calories: 480 },
      { id: 'berk1-3', name: 'Duck Confit', protein: 50, price: 46.00, calories: 620 },
    ],
  },
  {
    id: 'berk-2',
    name: 'Comal',
    type: 'Mexican',
    city: 'Berkeley',
    area: 'Downtown Berkeley',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/comal-berkeley',
    meals: [
      { id: 'berk2-1', name: 'Carne Asada Plate', protein: 50, price: 24.00, calories: 620 },
      { id: 'berk2-2', name: 'Chicken Mole', protein: 44, price: 22.00, calories: 580 },
      { id: 'berk2-3', name: 'Carnitas Tacos (2)', protein: 38, price: 18.00, calories: 520 },
    ],
  },
  {
    id: 'berk-3',
    name: 'Ippudo Berkeley',
    type: 'Japanese / Ramen',
    city: 'Berkeley',
    area: 'Downtown Berkeley',
    owned: 'Chain',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/ippudo-berkeley',
    meals: [
      { id: 'berk3-1', name: 'Akamaru Modern Ramen', protein: 28, price: 18.00, calories: 680 },
      { id: 'berk3-2', name: 'Karaka Spicy Ramen + Chashu', protein: 38, price: 22.00, calories: 720 },
      { id: 'berk3-3', name: 'Shiromaru Hakata Classic', protein: 26, price: 17.00, calories: 640 },
    ],
  },
  {
    id: 'berk-4',
    name: 'Imm Thai Street Food',
    type: 'Thai',
    city: 'Berkeley',
    area: 'Downtown Berkeley',
    owned: 'Independent',
    rating: 4.3,
    meals: [
      { id: 'berk4-1', name: 'Pad Thai with Chicken', protein: 32, price: 14.00, calories: 560 },
      { id: 'berk4-2', name: 'Basil Stir Fry + Rice', protein: 36, price: 15.00, calories: 520 },
      { id: 'berk4-3', name: 'Khao Soi', protein: 34, price: 16.00, calories: 640 },
    ],
  },
  {
    id: 'berk-5',
    name: "Gregoire",
    type: 'French / Takeout',
    city: 'Berkeley',
    area: 'Gourmet Ghetto',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/gregoire-berkeley',
    meals: [
      { id: 'berk5-1', name: 'Rotisserie Chicken Box', protein: 52, price: 18.00, calories: 560 },
      { id: 'berk5-2', name: 'Duck Confit Sandwich', protein: 40, price: 16.00, calories: 580 },
      { id: 'berk5-3', name: 'Steak Sandwich', protein: 44, price: 18.00, calories: 620 },
    ],
  },

  // ── SAN JOSE ───────────────────────────────────────────────────
  {
    id: 'sj-1',
    name: 'Adega',
    type: 'Portuguese',
    city: 'San Jose',
    area: 'Little Portugal',
    owned: 'Independent',
    rating: 4.7,
    yelp: 'https://www.yelp.com/biz/adega-san-jose',
    meals: [
      { id: 'sj1-1', name: 'Grilled Octopus', protein: 36, price: 28.00, calories: 360 },
      { id: 'sj1-2', name: 'Bacalhau (Salt Cod)', protein: 48, price: 34.00, calories: 480 },
      { id: 'sj1-3', name: 'Pork Tenderloin', protein: 52, price: 36.00, calories: 520 },
    ],
  },
  {
    id: 'sj-2',
    name: 'Pho Kim Long',
    type: 'Vietnamese',
    city: 'San Jose',
    area: 'Story Road',
    owned: 'Family-owned',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/pho-kim-long-san-jose',
    meals: [
      { id: 'sj2-1', name: 'Beef Pho (Large)', protein: 50, price: 11.00, calories: 540 },
      { id: 'sj2-2', name: 'Chicken Pho (Large)', protein: 44, price: 10.50, calories: 480 },
      { id: 'sj2-3', name: 'Bun Bo Hue', protein: 42, price: 11.50, calories: 520 },
    ],
  },
  {
    id: 'sj-3',
    name: 'Santana Row Grill',
    type: 'American / Steakhouse',
    city: 'San Jose',
    area: 'Santana Row',
    owned: 'Independent',
    rating: 4.2,
    meals: [
      { id: 'sj3-1', name: 'NY Strip Steak (10oz)', protein: 68, price: 48.00, calories: 680 },
      { id: 'sj3-2', name: 'Grilled Salmon', protein: 46, price: 32.00, calories: 480 },
      { id: 'sj3-3', name: 'BBQ Chicken Plate', protein: 52, price: 26.00, calories: 580 },
    ],
  },
  {
    id: 'sj-4',
    name: 'Mezcal',
    type: 'Mexican',
    city: 'San Jose',
    area: 'Downtown SJ',
    owned: 'Independent',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/mezcal-san-jose',
    meals: [
      { id: 'sj4-1', name: 'Carne Asada Burrito', protein: 48, price: 13.00, calories: 820 },
      { id: 'sj4-2', name: 'Pollo Asado Bowl', protein: 44, price: 12.50, calories: 640 },
      { id: 'sj4-3', name: 'Carnitas Plate', protein: 52, price: 15.00, calories: 700 },
    ],
  },
  {
    id: 'sj-5',
    name: 'Vegetarian House',
    type: 'Vegetarian / Chinese',
    city: 'San Jose',
    area: 'Downtown SJ',
    owned: 'Independent',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/vegetarian-house-san-jose',
    meals: [
      { id: 'sj5-1', name: 'Kung Pao Tofu', protein: 18, price: 14.00, calories: 380 },
      { id: 'sj5-2', name: 'Seitan Stir Fry', protein: 24, price: 15.00, calories: 360 },
      { id: 'sj5-3', name: 'Tempeh Fried Rice', protein: 20, price: 13.00, calories: 420 },
    ],
  },

  // ── SOUTH BAY / PENINSULA ──────────────────────────────────────
  {
    id: 'pen-1',
    name: 'Vesta',
    type: 'Pizza / Italian',
    city: 'Redwood City',
    area: 'Downtown',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/vesta-redwood-city',
    meals: [
      { id: 'pen1-1', name: 'Fennel Sausage Pizza', protein: 36, price: 22.00, calories: 780 },
      { id: 'pen1-2', name: 'Chicken Milanese', protein: 50, price: 28.00, calories: 620 },
      { id: 'pen1-3', name: 'Meatball Sub', protein: 42, price: 18.00, calories: 680 },
    ],
  },
  {
    id: 'pen-2',
    name: 'Bun Bo Hue An Nam',
    type: 'Vietnamese',
    city: 'San Mateo',
    area: 'Downtown San Mateo',
    owned: 'Family-owned',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/bun-bo-hue-an-nam-san-mateo',
    meals: [
      { id: 'pen2-1', name: 'Bun Bo Hue (Spicy Beef Noodle)', protein: 46, price: 11.50, calories: 540 },
      { id: 'pen2-2', name: 'Beef Pho', protein: 48, price: 11.00, calories: 510 },
      { id: 'pen2-3', name: 'Grilled Pork Rice Plate', protein: 40, price: 12.00, calories: 560 },
    ],
  },
  {
    id: 'pen-3',
    name: 'Flea St. Cafe',
    type: 'California / Organic',
    city: 'Menlo Park',
    area: 'El Camino Real',
    owned: 'Independent',
    rating: 4.3,
    meals: [
      { id: 'pen3-1', name: 'Grass-fed Burger', protein: 46, price: 22.00, calories: 680 },
      { id: 'pen3-2', name: 'Free-range Chicken', protein: 52, price: 28.00, calories: 560 },
      { id: 'pen3-3', name: 'Wild Salmon', protein: 44, price: 32.00, calories: 480 },
    ],
  },
  {
    id: 'pen-4',
    name: "Sura Korean Cuisine",
    type: 'Korean / BBQ',
    city: 'San Bruno',
    area: 'San Bruno Ave',
    owned: 'Family-owned',
    rating: 4.2,
    meals: [
      { id: 'pen4-1', name: 'Galbi (Short Rib) Set', protein: 58, price: 28.00, calories: 720 },
      { id: 'pen4-2', name: 'Bulgogi Plate + Rice', protein: 46, price: 19.00, calories: 620 },
      { id: 'pen4-3', name: 'Kimchi Jjigae with Pork', protein: 32, price: 16.00, calories: 480 },
    ],
  },
  {
    id: 'pen-5',
    name: 'La Corneta Taqueria',
    type: 'Mexican / Taqueria',
    city: 'San Bruno',
    area: 'San Mateo Ave',
    owned: 'Family-owned',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/la-corneta-taqueria-san-bruno',
    meals: [
      { id: 'pen5-1', name: 'Carne Asada Burrito', protein: 52, price: 10.50, calories: 880 },
      { id: 'pen5-2', name: 'Chicken Super Burrito', protein: 48, price: 10.00, calories: 820 },
      { id: 'pen5-3', name: 'Carnitas Plate', protein: 46, price: 12.00, calories: 720 },
      { id: 'pen5-4', name: 'Al Pastor Tacos (3)', protein: 38, price: 9.50, calories: 540 },
    ],
  },
  {
    id: 'pen-6',
    name: 'Curry Up Now',
    type: 'Indian / Fast Casual',
    city: 'Multiple',
    area: 'Bay Area chain',
    owned: 'Local chain',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/curry-up-now-san-francisco',
    meals: [
      { id: 'pen6-1', name: 'Tikka Masala Wrap', protein: 36, price: 14.00, calories: 640 },
      { id: 'pen6-2', name: 'Chicken Kati Roll', protein: 38, price: 13.50, calories: 580 },
      { id: 'pen6-3', name: 'Lamb Vindaloo Bowl', protein: 44, price: 17.00, calories: 560 },
    ],
  },

  // ── EAST BAY / FREMONT / HAYWARD ────────────────────────────────
  {
    id: 'eb-1',
    name: 'Rivoli',
    type: 'California / Mediterranean',
    city: 'Berkeley',
    area: 'Elmwood',
    owned: 'Independent',
    rating: 4.6,
    meals: [
      { id: 'eb1-1', name: 'Roasted Duck', protein: 54, price: 38.00, calories: 580 },
      { id: 'eb1-2', name: 'Lamb Chops', protein: 50, price: 42.00, calories: 540 },
      { id: 'eb1-3', name: 'Seared Halibut', protein: 46, price: 36.00, calories: 420 },
    ],
  },
  {
    id: 'eb-2',
    name: 'Pakwan',
    type: 'Pakistani / Indian',
    city: 'Fremont',
    area: 'Fremont Blvd',
    owned: 'Family-owned',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/pakwan-restaurant-fremont',
    meals: [
      { id: 'eb2-1', name: 'Chicken Karahi + Naan', protein: 50, price: 16.00, calories: 680 },
      { id: 'eb2-2', name: 'Lamb Biryani', protein: 48, price: 16.00, calories: 720 },
      { id: 'eb2-3', name: 'Seekh Kebab Plate', protein: 56, price: 17.00, calories: 620 },
    ],
  },
  {
    id: 'eb-3',
    name: 'Shalizaar',
    type: 'Persian',
    city: 'Belmont',
    area: 'El Camino Real',
    owned: 'Independent',
    rating: 4.6,
    yelp: 'https://www.yelp.com/biz/shalizaar-restaurant-belmont',
    meals: [
      { id: 'eb3-1', name: 'Koobideh Kebab Plate', protein: 62, price: 22.00, calories: 680 },
      { id: 'eb3-2', name: 'Chicken Joojeh', protein: 58, price: 24.00, calories: 580 },
      { id: 'eb3-3', name: 'Lamb Chenjeh', protein: 54, price: 28.00, calories: 560 },
    ],
  },
  {
    id: 'eb-4',
    name: 'Ohgane Korean BBQ',
    type: 'Korean BBQ',
    city: 'Oakland',
    area: 'Temescal',
    owned: 'Independent',
    rating: 4.3,
    yelp: 'https://www.yelp.com/biz/ohgane-korean-barbeque-restaurant-oakland',
    meals: [
      { id: 'eb4-1', name: 'AYCE BBQ (beef + pork)', protein: 80, price: 42.00, calories: 1200 },
      { id: 'eb4-2', name: 'Galbi Set', protein: 60, price: 36.00, calories: 740 },
      { id: 'eb4-3', name: 'Bulgogi + Rice', protein: 44, price: 22.00, calories: 620 },
    ],
  },
  {
    id: 'eb-5',
    name: 'Los Comales',
    type: 'Mexican',
    city: 'Hayward',
    area: 'Mission Blvd',
    owned: 'Family-owned',
    rating: 4.3,
    meals: [
      { id: 'eb5-1', name: 'Carne Asada Platter', protein: 56, price: 14.00, calories: 720 },
      { id: 'eb5-2', name: 'Pollo Asado Burrito', protein: 50, price: 10.00, calories: 840 },
      { id: 'eb5-3', name: 'Carnitas Tacos (3)', protein: 42, price: 9.50, calories: 540 },
    ],
  },

  // ── MARIN / NORTH BAY ───────────────────────────────────────────
  {
    id: 'mar-1',
    name: 'Sol Food',
    type: 'Puerto Rican',
    city: 'San Rafael',
    area: 'Downtown',
    owned: 'Independent',
    rating: 4.5,
    yelp: 'https://www.yelp.com/biz/sol-food-san-rafael',
    meals: [
      { id: 'mar1-1', name: 'Pernil (Roast Pork) Plate', protein: 56, price: 17.00, calories: 680 },
      { id: 'mar1-2', name: 'Pollo Guisado Plate', protein: 48, price: 15.00, calories: 620 },
      { id: 'mar1-3', name: 'Churrasco Steak Plate', protein: 52, price: 19.00, calories: 640 },
    ],
  },
  {
    id: 'mar-2',
    name: 'Buckeye Roadhouse',
    type: 'American / BBQ',
    city: 'Mill Valley',
    area: 'Panoramic Hwy',
    owned: 'Independent',
    rating: 4.4,
    yelp: 'https://www.yelp.com/biz/buckeye-roadhouse-mill-valley',
    meals: [
      { id: 'mar2-1', name: 'BBQ Baby Back Ribs (half rack)', protein: 58, price: 36.00, calories: 820 },
      { id: 'mar2-2', name: 'Rotisserie Chicken', protein: 60, price: 28.00, calories: 640 },
      { id: 'mar2-3', name: 'Grilled NY Strip', protein: 64, price: 48.00, calories: 680 },
    ],
  },

  // ── CHAINS WITH REAL NUTRITION DATA ────────────────────────────
  {
    id: 'chain-1',
    name: "Panera Bread",
    type: 'Bakery / Café',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Chain',
    rating: 3.9,
    meals: [
      { id: 'ch1-1', name: 'Steak & White Cheddar Sandwich', protein: 34, price: 12.99, calories: 530 },
      { id: 'ch1-2', name: 'Mediterranean Veggie Sandwich', protein: 14, price: 11.99, calories: 440 },
      { id: 'ch1-3', name: 'Turkey Bacon Bravo', protein: 36, price: 12.49, calories: 580 },
      { id: 'ch1-4', name: 'Chicken Tikka Masala Soup Bowl', protein: 18, price: 10.99, calories: 360 },
    ],
  },
  {
    id: 'chain-2',
    name: "Sweetgreen",
    type: 'Salads / Bowls',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Chain',
    rating: 4.2,
    meals: [
      { id: 'ch2-1', name: 'Shroomami Bowl', protein: 22, price: 15.95, calories: 465 },
      { id: 'ch2-2', name: 'Hot Honey Chicken Bowl', protein: 44, price: 17.95, calories: 640 },
      { id: 'ch2-3', name: 'Steak & Blue Cheese Salad', protein: 38, price: 17.95, calories: 560 },
      { id: 'ch2-4', name: 'Harvest Bowl', protein: 30, price: 16.95, calories: 705 },
    ],
  },
  {
    id: 'chain-3',
    name: 'CAVA',
    type: 'Mediterranean / Bowls',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Chain',
    rating: 4.3,
    meals: [
      { id: 'ch3-1', name: 'Grilled Chicken Bowl', protein: 48, price: 13.45, calories: 580 },
      { id: 'ch3-2', name: 'Lamb & Beef Meatball Bowl', protein: 44, price: 14.45, calories: 620 },
      { id: 'ch3-3', name: 'Steak Bowl', protein: 42, price: 14.95, calories: 600 },
      { id: 'ch3-4', name: 'Falafel + Chicken Combo Bowl', protein: 52, price: 15.45, calories: 660 },
    ],
  },
  {
    id: 'chain-4',
    name: "MOD Pizza",
    type: 'Pizza / Fast Casual',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Chain',
    rating: 4.0,
    meals: [
      { id: 'ch4-1', name: 'Pepperoni + Sausage MOD-size', protein: 38, price: 10.97, calories: 820 },
      { id: 'ch4-2', name: 'Chicken + Roasted Garlic MOD', protein: 42, price: 10.97, calories: 740 },
      { id: 'ch4-3', name: 'Mega MOD (double toppings)', protein: 50, price: 13.97, calories: 980 },
    ],
  },
  {
    id: 'chain-5',
    name: "Tender Loving Empire / Tender Butter",
    type: 'Chicken / Fast Casual',
    city: 'San Francisco',
    area: 'Multiple locations',
    owned: 'Local chain',
    rating: 4.4,
    meals: [
      { id: 'ch5-1', name: 'Crispy Chicken Sandwich', protein: 48, price: 14.00, calories: 640 },
      { id: 'ch5-2', name: 'Chicken Tenders (4pc)', protein: 44, price: 13.00, calories: 560 },
      { id: 'ch5-3', name: 'Spicy Chicken Sandwich', protein: 46, price: 14.50, calories: 660 },
    ],
  },
  {
    id: 'chain-6',
    name: 'In-N-Out Burger',
    type: 'Burgers / Fast Food',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Chain',
    rating: 4.5,
    meals: [
      { id: 'ch6-1', name: 'Double-Double', protein: 37, price: 6.70, calories: 670 },
      { id: 'ch6-2', name: '3x3 (3 patties)', protein: 53, price: 8.10, calories: 860 },
      { id: 'ch6-3', name: '4x4 (4 patties)', protein: 69, price: 9.50, calories: 1050 },
      { id: 'ch6-4', name: 'Protein Style Double-Double', protein: 33, price: 6.70, calories: 340 },
    ],
  },
  {
    id: 'chain-7',
    name: "Philz Coffee + Snacks",
    type: 'Café / Light Bites',
    city: 'Multiple',
    area: 'Bay Area wide',
    owned: 'Local chain',
    rating: 4.4,
    meals: [
      { id: 'ch7-1', name: 'Egg & Cheese Sandwich', protein: 18, price: 8.50, calories: 380 },
      { id: 'ch7-2', name: 'Turkey Pesto Sandwich', protein: 26, price: 11.00, calories: 440 },
    ],
  },
]

// Add protein efficiency to each meal
export const RESTAURANTS_WITH_EFFICIENCY = BAY_AREA_RESTAURANTS.map(r => ({
  ...r,
  meals: r.meals.map(m => ({
    ...m,
    efficiency: parseFloat((m.protein / m.price).toFixed(1)),
  })),
}))

// Legacy export (used by older code paths)
export const RESTAURANTS = BAY_AREA_RESTAURANTS

// Default user profile
export const DEFAULT_PROFILE = {
  name: 'Alex',
  dailyProteinGoal: 160,
  dailyBudget: 30,
  dietPreference: 'No restrictions',
  location: 'San Bruno, CA',
}
